language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t duong120798/react-app-dev:ci -f Dockerfile.dev .

script:
  - docker run duong120798/react-app-dev:ci -e CI=true npm run test -- --coverage
