version: '3'

services:
  react-app:
    container_name: 'react-app'
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
          - ./:/usr/src/app
          - /usr/src/app/node_modules
  test-react-app:
    container_name: 'test-react-app'
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    stdin_open: true
    working_dir: /usr/src/app
    volumes:
          - ./:/usr/src/app
          - /usr/src/app/node_modules
    command: ["npm", "run", "test"]
